
- hosts: localhost
  connection: local
  tasks:
    - name: Add tower user
      tower_user:
        username: cli_user
        password: password
        email: jdoe@example.org
        first_name: John
        last_name: Doe
        state: present
        superuser: yes
        tower_config_file: "~/tower_cli.cfg"

    - name: Create tower organization
      tower_organization:
        name: "Default"
        description: "default organization"
        state: present
        tower_config_file: "~/tower_cli.cfg"